version: '3.0'
services:
  proxy:
    container_name: "proxy"
    image: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      PORT: '3000'
    depends_on:
      - resource_server
      - auth_server
    restart: 'always'

  resource_server:
    container_name: 'resource_server'
    build:
      context: ./../../..
      dockerfile: ./apps/backend/build/docker/dev.Dockerfile
    volumes:
      - ./../../../apps/backend:/app/apps/backend
      - ./../../../apps/shared:/app/apps/shared
    ports:
      - '3002:3000'
    depends_on:
      - database
    env_file:
      - .env
    restart: 'always'

  auth_server:
    container_name: 'auth_server'
    build:
      context: ./../../..
      dockerfile: ./apps/auth/build/docker/dev.Dockerfile
    volumes:
      - ./../../../apps/auth:/app/apps/auth
      - ./../../../apps/shared:/app/apps/shared
    ports:
      - '3003:3000'
    depends_on:
      - database
    env_file:
      - .auth.env
    restart: 'always'

  database:
    container_name: 'database'
    image: 'mariadb:10.5.8'
    ports:
      - "3308:3306"
    volumes:
      - diploma_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'diploma'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    restart: 'always'

  redis:
    container_name: 'redis'
    image: 'redis:7.0.7'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    restart: 'always'
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
volumes:
  diploma_data:
  redis-data:
  redis-conf:
